//+build wireinject

// The build tag makes sure the stub is not built in the final build.
package app

import (
	"github.com/google/wire"
	"mmrath.com/gobase/client/account"
	"mmrath.com/gobase/client/config"
	"mmrath.com/gobase/pkg/auth"
	"mmrath.com/gobase/pkg/email"
)

func ProvideJWTConfig(config config.Config) auth.JWTConfig {
	return config.JWT
}

func ProvideSMTPConfig(config config.Config) email.SMTPConfig {
	return config.SMTP
}

func BuildServer(config config.Config, mailer email.Mailer) (*Server, error) {
	//This is stub code, actual implementation will be generated by wire
	wire.Build(
		ProvideJWTConfig,
		NewDB,
		NewNotifier,
		NewServer,
		NewMux,
		auth.NewJWTService,
		account.NewResource,
		account.NewService,
	)
	return &Server{}, nil
}
