version: "3"

services:
  clipo-web:
    image: node:lts
    command: sh -c "yarn && yarn start clipo --proxy-config proxy.conf.js --base-href=/clipo/"
    environment:
      - NODE_ENV=development
      - API_PROXY=http://clipo:9010
    ports:
      - "8010:4200"
    working_dir: /root/web
    volumes:
      - ./web:/root/web:cached

  admin-web:
    image: node:lts
    command: sh -c "yarn && yarn start admin --proxy-config proxy.conf.js --base-href=/admin/"
    environment:
      - NODE_ENV=development
    ports:
      - "8020:4200"
    working_dir: /root/web
    volumes:
      - ./web:/root/web:cached

  clipo:
    image: golang:latest
    command: sh -c "./build-and-run.sh clipo"
    env_file:
      - ./go/apps/clipo/local.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    depends_on:
      - db-migration
      - mail
    ports:
      - "9010:9010"
    working_dir: /root/go
    volumes:
      - .:/root

  db:
    image: "postgres:12-alpine"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - pg_data:/var/lib/postgresql/data

  db-migration:
    image: golang:latest
    command: sh -c "go run ./apps/db-migration"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_ADMIN_USERNAME}
      - DB_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    depends_on:
      - db
    working_dir: /root/go
    volumes:
      - .:/root:cached

  mail:
    image: inbucket/inbucket:latest
    restart: always
    ports:
      - 1100:1100
      - 8025:9000
      - 2500:2500

volumes:
  pg_data:
