//+build wireinject
// The build tag makes sure the stub is not built in the final build.

package app

import (
	"net/http"

	"github.com/google/wire"

	"github.com/mmrath/gobase/common/email"
	"github.com/mmrath/gobase/uaa/uaa-server/internal/account"
)

func BuildServer(mailer email.Mailer) *http.Server {
	//This is stub code, actual implementation will be generated by wire
	panic(wire.Build(
		LoadConfig,
		NewDB,
		HttpRouter,
		NewAppRouter,
		NewHttpServer,
		account.Provider,
	))

	return nil
}
