version: "3"

services:
  clipo:
    image: golang:latest
    command:     sh -c "
      ../scripts/wait-for-it.sh db:5432 -t 10 -- ./build-and-run.sh clipo"
    env_file:
      - ./apps/clipo/local.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=app_user
      - DB_PASSWORD=${APP_DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}

    depends_on:
      - db
      - db-migration
      - mail
    ports:
      - "${ENV_PORT_PREFIX}10:9010"
    working_dir: /root/go
    volumes:
      - ..:/root:cached

  db-migration:
    image: golang:latest
    command: sh -c "../scripts/wait-for-it.sh db:5432 -t 10 -- ./build.sh db-migration && ${GOPATH}/bin/db-migration"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - MIGRATION_DIR=./apps/db-migration/resources/migrations
    depends_on:
      - db
    working_dir: /root/go
    volumes:
      - ..:/root:cached

  db:
    image: "postgres:12"
    ports:
      - "${ENV_PORT_PREFIX}32:5432"
    environment:
      - POSTGRES_USER=${DB_ADMIN_USERNAME}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - APP_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./apps/db-migration/resources/scripts/init:/docker-entrypoint-initdb.d/

  mail:
    image: inbucket/inbucket:latest
    restart: always
    ports:
      - ${ENV_PORT_PREFIX}11:1100
      - ${ENV_PORT_PREFIX}12:9000
      - ${ENV_PORT_PREFIX}13:2500

