version: "3"

services:
  clipo:
    image: golang:latest
    command: sh -c "./build-and-run.sh clipo"
    environment:
      - APP_DOMAIN_NAME=${APP_DOMAIN_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - SMTP_HOST=mail
      - SMTP_PORT=2500
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_TEMPLATE_PATH=./apps/clipo/resources/templates/email
    depends_on:
      - db-migration
      - mail
    ports:
      - "9010:9010"
    working_dir: /root/go
    volumes:
      - ..:/root:cached
      - $GOPATH/pkg/mod:/go/pkg/mod

  db:
    image: "postgres:12"
    ports:
      - "${ENV_PORT_PREFIX}32:5432"
    environment:
      - POSTGRES_USER=${DB_ADMIN_USERNAME}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - APP_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./apps/db-migration/resources/scripts/init:/docker-entrypoint-initdb.d/

  db-migration:
    image: golang:latest
    command: sh -c "go run ./apps/db-migration"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_ADMIN_USERNAME}
      - DB_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - MIGRATION_DIR=./apps/db-migration/resources/migrations
    depends_on:
      - db
    working_dir: /root/go
    volumes:
      - ..:/root:cached
      - $GOPATH/pkg/mod:/go/pkg/mod

  mail:
    image: inbucket/inbucket:latest
    restart: always
    ports:
      - 1100:1100
      - 8025:9000
      - 2500:2500

volumes:
  pg_data:
