//+build wireinject

// The build tag makes sure the stub is not built in the final build.
package app

import (
	"github.com/google/wire"
	"github.com/mmrath/gobase/client/account"
	"github.com/mmrath/gobase/common/auth"
	"github.com/mmrath/gobase/common/email"
)

func ProvideJWTConfig(config Config) auth.JWTConfig {
	return config.JWT
}

func ProvideSMTPConfig(config Config) email.SMTPConfig {
	return config.SMTP
}

func BuildServer(config Config, mailer email.Mailer) (*Server, error) {
	//This is stub code, actual implementation will be generated by wire
	wire.Build(
		ProvideJWTConfig,
		NewDB,
		NewNotifier,
		NewServer,
		NewMux,
		auth.NewJWTService,
		account.NewResource,
		account.NewService,
	)
	return &Server{}, nil
}
