//+build wireinject

// The build tag makes sure the stub is not built in the final build.
package cmd

import (
	"github.com/google/wire"
	"github.com/mmrath/gobase/go/apps/clipo/internal/account"
	"github.com/mmrath/gobase/go/pkg/auth"
	"github.com/mmrath/gobase/go/pkg/email"
)

func ProvideJWTConfig(config Config) auth.JWTConfig {
	return config.JWT
}

func ProvideSMTPConfig(config Config) email.SMTPConfig {
	return config.SMTP
}

func BuildServer(config Config, mailer email.Mailer) (*App, error) {
	//This is stub code, actual implementation will be generated by wire
	wire.Build(
		ProvideJWTConfig,
		NewDB,
		NewNotifier,
		NewApp,
		NewMux,
		auth.NewJWTService,
		account.NewResource,
		account.NewService,
	)
	return &App{}, nil
}
